services:
  - type: web
    name: django-blog
    env: python
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate"
    startCommand: "gunicorn blogproject.wsgi:application"
    envVars:
      - key: DEBUG
        value: "False"
